server:
  port: ${SERVER_PORT:8089}
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:slt-marketplacer}?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER:postgres}
    password: ${DB_PWD:1234}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_HOST:http://localhost:8080}/realms/${KEYCLOAK_RELAM:quickstart}/protocol/openid-connect/certs


springdoc:
  swagger-ui:
    enabled: true
    path: /api/docs/swagger-ui.html
    syntaxHighlight:
      activated: true

  api-docs:
    path: /api/docs
