server:
  port: ${SERVER_PORT:8089}
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:slt-marketplacer}?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PWD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_TARGET_REALM:marketplacer}/protocol/openid-connect/certs


springdoc:
  swagger-ui:
    enabled: true
    path: /api/docs/swagger-ui.html
    syntaxHighlight:
      activated: true

  api-docs:
    path: /api/docs

aws:
  accessKey: ${AWS_ACCESS_KEY:accessKey}
  secretKey: ${AWS_SECRET_KEY:secretKey}
  region: ${AWS_REGION:region}
  s3:
    bucket: ${S3_BUCKET_NAME:bucket}

keycloak:
  baseUrl: ${KEYCLOAK_BASE_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:master}
  targetRealm: ${KEYCLOAK_TARGET_REALM:marketplacer}
  adminClientId: ${KEYCLOAK_ADMIN_CLIENT_ID:marketplacer-backend}
  adminClientSecret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:xxxx}
