server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/slt-marketplacer?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: marketplacer-backend
            client-secret: fcd16ac0-d243-4da5-95ef-c889d6fdeef9
            authorization-grant-type: authorization_code
            scope: openid

        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/marketplacer
            user-name-attribute: preferred_username
