apiVersion: v1
kind: Service
metadata:
  name: marketplacer-backend-service
spec:
  selector:
    app: marketplacer-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
  type: LoadBalancer
